### PR TITLE
Create CODE_OF_CONDUCT.md

### LINKED ISSUE #25: Code of Conduct file
Code of conduct is very important for the repository. It reflects the good value of the repository.

I am LGM-SOC participant. Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Yash-Sakre**
closes #25  
Create CODE_OF_CONDUCT.md file in repository

### CODE REVIEW

**Comment by akshitadixit** [comment]
@Yash-Sakre please note the edit I made in your comment. Words like `closes` `fixes` automatically link your issue to be closed when the PR is merged. Just some good open source practice :)

**Review by akshitadixit — APPROVED** [review]
Well written @Yash-Sakre  where did you copy it from though XD

**Comment by Yash-Sakre** [comment]
@akshitadixit It's a template given by GitHub itself.

**Comment by akshitadixit** [comment]
> @akshitadixit It's a template given by GitHub itself.

ah! how'd I miss it

**Pull request merged**
