### PR TITLE
Added issue templates 

### LINKED ISSUE #50: Add issue templates
We can add issue templates for this project and automate it 
when contributors try to create a new issue

I would like to work on this please assign me @akshitadixit

### PR DESCRIPTION
**Pull request by coding-geek21**
Added issue templates for bug_report,documentation and feature request

fixes: #50

### CODE REVIEW

**Review by akshitadixit — COMMENTED** [review]
I believe you wrote `create issue template and automate it` in #50

**Comment by coding-geek21** [comment]
> I believe you wrote `create issue template and automate it` in #50

Yes actually @akshitadixit it will get added automatically while creating a new issue 

https://www.awesomescreenshot.com/video/4251080?key=2305a91eb60dfe589d332b11efaefe89

**Comment by coding-geek21** [comment]
@akshitadixit Kindly please add the level label

**Comment by akshitadixit** [comment]
My bad, almost missed out on it.

**Pull request merged**
