### PR TITLE
Issue number #9 is solved, Readme file updated with contribution Info

### LINKED ISSUE #9: Update Readme file to help beginners contribute to open source
Hello, I am a LGM-SOC'21 Participant
I am a Newbie coder And a beginner to open source contributions, I learnt open source contributions recently so I would like to update this Readme file where I will give some detailed steps to contribute to this project so that the Readme file can be more beginner friendly.
Assign this issue to me.

### PR DESCRIPTION
**Pull request by Vedant-Jayesh-Oza**
@akshitadixit The issue Number #9 which was assigned to me is been solved. The Readme file has been updated with the steps following which a newbie coder can contribute to open source projects. Merge this PR in the main Repository

### CODE REVIEW

**Review by akshitadixit — APPROVED** [review]
Looks good! Also, I appreciate how you created a new branch for the PR :)

**Comment by Vedant-Jayesh-Oza** [comment]
@akshitadixit Thank you so much 😁 btw  when will we get to know whether the PRs are merged  ?

**Comment by akshitadixit** [comment]
@Vedant-Jayesh-Oza now you can add yourself to the contributors list :)

**Comment by Vedant-Jayesh-Oza** [comment]
Great will do that 👍

**Pull request merged**
