### PR TITLE
Create new branch web-app

### LINKED ISSUE #7: Add a new branch
For beginners.
Kindly add a new branch with the name web-app.
To create a new branch you need to open your git (from the bash, terminal, or vs-code, wherever you use it from) and follow these steps:
* `git checkout -b web-app` {to create a new branch and switch to it}
* `git rm -rf .` {to remove(rm) all files from the branch}
* Add a fresh README.md that specifies that this branch is for the webapp development
* `git add .`
* `git commit -m "Create new branch web-app"`
* `git push origin web-app`
* Then make a PR

### PR DESCRIPTION
**Pull request by supzi-del**
closes #7 

Is this okay?

### CODE REVIEW

**Review by akshitadixit — CHANGES_REQUESTED** [review]
Hey @supzi-del everything is okay, just that you forgot to add the fresh README.md file mentioned in #7 
Please add that and push it. The changes will be reflected in this PR.

**Comment by supzi-del** [comment]
Oh okay, where should I add it?

**Comment by supzi-del** [comment]
I have created a folder called README.md in the folder of VCallZer. What should I do next?

**Comment by akshitadixit** [comment]
> Oh okay, where should I add it?

In the web-app branch

**Comment by akshitadixit** [comment]
> I have created a folder called README.md in the folder of VCallZer. What should I do next?

You may now make a commit and push to your repo. Your PR will show those changes automatically.

**Comment by akshitadixit** [comment]
> I have created a folder called README.md in the folder of VCallZer. What should I do next?

Commit the file and push to your repo using `git push web-app` and your changes will automatically be seen here

**Review by akshitadixit — APPROVED** [review]
Great, thank you!

**Comment by supzi-del** [comment]
Thanks for guiding!

**Comment by akshitadixit** [comment]
@supzi-del you're welcome, just make sure the next time you make a PR use the words `closes` or `fixes` with the issue number as I edited in your description above. This automatically links the issue and closes it when the PR is merged. Just some good open-source practice :)

**Comment by supzi-del** [comment]
Hey! did anything go wrong from my side?

**Comment by akshitadixit** [comment]
> Hey! did anything go wrong from my side?

Hey @supzi-del I forgot to check the merge destination. 
The next time you push a new branch to a repo, please do not select the destination as main. I did overlook this, my bad.
image

**Comment by supzi-del** [comment]
I'm so sorry! I will keep it in mind.

**Pull request merged**
