### PR TITLE
Added extra information to the readme

### PR DESCRIPTION
**Pull request by erichamers**
- [x] Add the information in the image below in the readme.

### CODE REVIEW

**Comment by akshitadixit** [comment]
@erichamers are you a participant of LGM SOC?

**Comment by erichamers** [comment]
> @erichamers are you a participant of LGM SOC?

no

**Comment by akshitadixit** [comment]
@erichamers hey, anything up?

**Comment by erichamers** [comment]
I think #32 merges the same thing and more.

**Comment by akshitadixit** [comment]
Sorry about that, but your PR would've definitely gotten the upper hand since it came in first. Anyway, thank you for taking time out to contribute :) pick up anything else you'd like or create fresh issues.

**Comment by erichamers** [comment]
@akshitadixit no worries. glad to see an even better one was merged 😁

**Pull request closed without merging**
